string myName = "Волков Борис";
string groupName = "ИСП-252";
int courseNumber = 2;
double averageGrade = 4.6;
bool isBudget = true;
System.Console.WriteLine("Знакомство");
System.Console.WriteLine($"Студент: {myName}");
System.Console.WriteLine($"Группа: {groupName}");
System.Console.WriteLine($"Курс: {courseNumber}");
System.Console.WriteLine($"Средний балл: {averageGrade}");
System.Console.WriteLine($"Бюджетное место: {isBudget}");